package ru.markov.sqlvisualization.table;
// Generated 26.04.2019 10:58:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Attribute generated by hbm2java
 */
public class Attribute implements java.io.Serializable {

    private Integer idAttribute;
    private Entity entity;
    private String nameAttribute;
    private Set values = new HashSet(0);

    public Attribute() {
    }

    public Attribute(Entity entity, String nameAttribute) {
        this.entity = entity;
        this.nameAttribute = nameAttribute;
    }

    public Attribute(Entity entity, String nameAttribute, Set values) {
        this.entity = entity;
        this.nameAttribute = nameAttribute;
        this.values = values;
    }

    public Attribute(Integer idAttribute, String nameAttribute, Entity entity) {
        this.entity = entity;
        this.nameAttribute = nameAttribute;
        this.idAttribute = idAttribute;
    }

    public Integer getIdAttribute() {
        return this.idAttribute;
    }

    public void setIdAttribute(Integer idAttribute) {
        this.idAttribute = idAttribute;
    }

    public Entity getEntity() {
        return this.entity;
    }

    public void setEntity(Entity entity) {
        this.entity = entity;
    }

    public String getNameAttribute() {
        return this.nameAttribute;
    }

    public void setNameAttribute(String nameAttribute) {
        this.nameAttribute = nameAttribute;
    }

    public Set getValues() {
        return this.values;
    }

    public void setValues(Set values) {
        this.values = values;
    }

    @Override
    public String toString() {
        return entity.toString() + " " + nameAttribute;
    }

}
