package ru.markov.sqlvisualization.table;
// Generated 26.04.2019 10:58:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entity generated by hbm2java
 */
public class Entity  implements java.io.Serializable {


     private Integer idEntity;
     private String nameEntity;
     private Set attributes = new HashSet(0);

    public Entity() {
    }

	
    public Entity(String nameEntity) {
        this.nameEntity = nameEntity;
    }
    public Entity(String nameEntity, Set attributes) {
       this.nameEntity = nameEntity;
       this.attributes = attributes;
    }
    public Entity(Integer idEntity, String nameEntity) {
       this.nameEntity = nameEntity;
       this.idEntity = idEntity;
    }
   
    public Integer getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(Integer idEntity) {
        this.idEntity = idEntity;
    }
    public String getNameEntity() {
        return this.nameEntity;
    }
    
    public void setNameEntity(String nameEntity) {
        this.nameEntity = nameEntity;
    }
    public Set getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(Set attributes) {
        this.attributes = attributes;
    }

    @Override
    public String toString() {
        return nameEntity;
    }
    
    




}


