package ru.markov.sqlvisualization.table;
// Generated 26.04.2019 10:58:21 by Hibernate Tools 4.3.1



/**
 * Value generated by hbm2java
 */
public class Value  implements java.io.Serializable {


     private Integer idValue;
     private Attribute attribute;
     private String value;
     private int rowNumber;

    public Value() {
    }

    public Value(Attribute attribute, String value, int rowNumber) {
       this.attribute = attribute;
       this.value = value;
       this.rowNumber = rowNumber;
    }
   
    public Integer getIdValue() {
        return this.idValue;
    }
    
    public void setIdValue(Integer idValue) {
        this.idValue = idValue;
    }
    public Attribute getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public int getRowNumber() {
        return this.rowNumber;
    }
    
    public void setRowNumber(int rowNumber) {
        this.rowNumber = rowNumber;
    }

    @Override
    public String toString() {
        return attribute.toString()+" "+value;
    }


    


}


